export const VALID_THEMES = ["dark", "light", "cyberpunk", "forest"] as const;

export type Theme = (typeof VALID_THEMES)[number];

export function isValidTheme(value: string | null): value is Theme {
  return value !== null && (VALID_THEMES as readonly string[]).includes(value);
}

export const THEME_VARIABLES = [
  "--color-primary",
  "--color-primary-contrast",
  "--color-primary-hover",
  "--color-accent",
  "--color-accent-contrast",
  "--color-accent-hover",
  "--color-border",
  "--color-background",
  "--color-foreground",
  "--color-text",
  "--color-text-secondary",
  "--color-success",
  "--color-success-contrast",
  "--color-error",
  "--color-error-contrast",
  "--color-warning",
  "--color-warning-contrast",
  "--color-info",
  "--color-info-contrast",
  "--logo-filter",
] as const;

export type ThemeVariable = (typeof THEME_VARIABLES)[number];

export const THEMES: Record<Theme, Record<ThemeVariable, string>> = {
  light: {
    "--color-primary": "var(--color-neutral-950)",
    "--color-primary-contrast": "var(--color-neutral-50)",
    "--color-primary-hover": "var(--color-neutral-700)",
    "--color-accent": "var(--color-neutral-300)",
    "--color-accent-contrast": "var(--color-neutral-950)",
    "--color-accent-hover": "var(--color-neutral-400)",
    "--color-border": "var(--color-neutral-300)",
    "--color-background": "var(--color-neutral-50)",
    "--color-foreground": "var(--color-neutral-100)",
    "--color-text": "var(--color-neutral-950)",
    "--color-text-secondary": "var(--color-neutral-700)",
    "--color-success": "var(--color-green-600)",
    "--color-success-contrast": "var(--color-green-50)",
    "--color-error": "var(--color-red-600)",
    "--color-error-contrast": "var(--color-red-50)",
    "--color-warning": "var(--color-amber-500)",
    "--color-warning-contrast": "var(--color-amber-950)",
    "--color-info": "var(--color-blue-600)",
    "--color-info-contrast": "var(--color-blue-50)",
    "--logo-filter": "brightness(0)",
  },
  dark: {
    "--color-primary": "var(--color-neutral-50)",
    "--color-primary-contrast": "var(--color-neutral-950)",
    "--color-primary-hover": "var(--color-neutral-300)",
    "--color-accent": "var(--color-neutral-500)",
    "--color-accent-contrast": "var(--color-neutral-950)",
    "--color-accent-hover": "var(--color-neutral-400)",
    "--color-border": "var(--color-neutral-600)",
    "--color-background": "var(--color-neutral-900)",
    "--color-foreground": "var(--color-neutral-800)",
    "--color-text": "var(--color-neutral-50)",
    "--color-text-secondary": "var(--color-neutral-200)",
    "--color-success": "var(--color-green-500)",
    "--color-success-contrast": "var(--color-green-950)",
    "--color-error": "var(--color-red-500)",
    "--color-error-contrast": "var(--color-red-950)",
    "--color-warning": "var(--color-amber-400)",
    "--color-warning-contrast": "var(--color-amber-950)",
    "--color-info": "var(--color-blue-400)",
    "--color-info-contrast": "var(--color-blue-950)",
    "--logo-filter": "brightness(0) invert(1)",
  },
  cyberpunk: {
    "--color-primary": "var(--color-fuchsia-500)",
    "--color-primary-contrast": "var(--color-fuchsia-50)",
    "--color-primary-hover": "var(--color-fuchsia-600)",
    "--color-accent": "var(--color-cyan-400)",
    "--color-accent-contrast": "var(--color-cyan-950)",
    "--color-accent-hover": "var(--color-cyan-500)",
    "--color-border": "var(--color-fuchsia-900)",
    "--color-background": "var(--color-slate-950)",
    "--color-foreground": "var(--color-slate-900)",
    "--color-text": "var(--color-fuchsia-50)",
    "--color-text-secondary": "var(--color-fuchsia-200)",
    "--color-success": "var(--color-lime-400)",
    "--color-success-contrast": "var(--color-lime-950)",
    "--color-error": "var(--color-rose-500)",
    "--color-error-contrast": "var(--color-rose-50)",
    "--color-warning": "var(--color-yellow-400)",
    "--color-warning-contrast": "var(--color-yellow-950)",
    "--color-info": "var(--color-sky-400)",
    "--color-info-contrast": "var(--color-sky-950)",
    "--logo-filter": "brightness(0) invert(1)",
  },
  forest: {
    "--color-primary": "var(--color-emerald-600)",
    "--color-primary-contrast": "var(--color-emerald-50)",
    "--color-primary-hover": "var(--color-emerald-700)",
    "--color-accent": "var(--color-orange-400)",
    "--color-accent-contrast": "var(--color-orange-950)",
    "--color-accent-hover": "var(--color-orange-500)",
    "--color-border": "var(--color-emerald-800)",
    "--color-background": "var(--color-stone-950)",
    "--color-foreground": "var(--color-stone-900)",
    "--color-text": "var(--color-stone-50)",
    "--color-text-secondary": "var(--color-stone-300)",
    "--color-success": "var(--color-teal-500)",
    "--color-success-contrast": "var(--color-teal-950)",
    "--color-error": "var(--color-red-500)",
    "--color-error-contrast": "var(--color-red-50)",
    "--color-warning": "var(--color-amber-400)",
    "--color-warning-contrast": "var(--color-amber-950)",
    "--color-info": "var(--color-sky-500)",
    "--color-info-contrast": "var(--color-sky-950)",
    "--logo-filter": "brightness(0) invert(1)",
  },
};
