export const VALID_THEMES = ["dark", "light", "cyberpunk", "forest"] as const;

export type Theme = (typeof VALID_THEMES)[number];

export function isValidTheme(value: string | null): value is Theme {
  return value !== null && (VALID_THEMES as readonly string[]).includes(value);
}

export const THEME_VARIABLES = [
  "--color-primary",
  "--color-primary-contrast",
  "--color-primary-hover",
  "--color-accent",
  "--color-accent-contrast",
  "--color-accent-hover",
  "--color-border",
  "--color-background",
  "--color-foreground",
  "--color-text",
  "--color-text-secondary",
  "--color-success",
  "--color-success-contrast",
  "--color-success-light",
  "--color-success-dark",
  "--color-error",
  "--color-error-contrast",
  "--color-error-dark",
  "--color-error-light",
  "--color-warning",
  "--color-warning-contrast",
  "--color-warning-light",
  "--color-warning-dark",
  "--color-info",
  "--color-info-contrast",
  "--color-info-dark",
  "--color-info-light",
  "--logo-filter",
] as const;

export type ThemeVariable = (typeof THEME_VARIABLES)[number];

export const THEMES: Record<Theme, Record<ThemeVariable, string>> = {
  light: {
    "--color-primary": "var(--color-neutral-950)",
    "--color-primary-contrast": "var(--color-neutral-50)",
    "--color-primary-hover": "var(--color-neutral-700)",
    "--color-accent": "var(--color-neutral-300)",
    "--color-accent-contrast": "var(--color-neutral-950)",
    "--color-accent-hover": "var(--color-neutral-400)",
    "--color-border": "var(--color-neutral-300)",
    "--color-background": "var(--color-neutral-50)",
    "--color-foreground": "var(--color-neutral-100)",
    "--color-text": "var(--color-neutral-950)",
    "--color-text-secondary": "var(--color-neutral-700)",
    "--color-success": "var(--color-green-600)",
    "--color-success-contrast": "var(--color-green-50)",
    "--color-success-dark": "var(--color-green-800)",
    "--color-success-light": "var(--color-green-100)",
    "--color-error": "var(--color-red-600)",
    "--color-error-contrast": "var(--color-red-50)",
    "--color-error-dark": "var(--color-red-800)",
    "--color-error-light": "var(--color-red-100)",
    "--color-warning": "var(--color-amber-500)",
    "--color-warning-contrast": "var(--color-amber-50)",
    "--color-warning-dark": "var(--color-amber-800)",
    "--color-warning-light": "var(--color-amber-100)",
    "--color-info": "var(--color-blue-500)",
    "--color-info-contrast": "var(--color-blue-50)",
    "--color-info-dark": "var(--color-blue-800)",
    "--color-info-light": "var(--color-blue-100)",
    "--logo-filter": "brightness(0)",
  },
  dark: {
    "--color-primary": "var(--color-neutral-50)",
    "--color-primary-contrast": "var(--color-neutral-950)",
    "--color-primary-hover": "var(--color-neutral-300)",
    "--color-accent": "var(--color-neutral-500)",
    "--color-accent-contrast": "var(--color-neutral-950)",
    "--color-accent-hover": "var(--color-neutral-400)",
    "--color-border": "var(--color-neutral-600)",
    "--color-background": "var(--color-neutral-900)",
    "--color-foreground": "var(--color-neutral-800)",
    "--color-text": "var(--color-neutral-50)",
    "--color-text-secondary": "var(--color-neutral-200)",
    "--color-success": "var(--color-emerald-500)",
    "--color-success-contrast": "var(--color-emerald-50)",
    "--color-success-dark": "var(--color-emerald-800)",
    "--color-success-light": "var(--color-emerald-100)",
    "--color-error": "var(--color-red-500)",
    "--color-error-contrast": "var(--color-red-50)",
    "--color-error-dark": "var(--color-red-800)",
    "--color-error-light": "var(--color-red-100)",
    "--color-warning": "var(--color-yellow-400)",
    "--color-warning-contrast": "var(--color-yellow-50)",
    "--color-warning-dark": "var(--color-yellow-800)",
    "--color-warning-light": "var(--color-yellow-100)",
    "--color-info": "var(--color-blue-400)",
    "--color-info-contrast": "var(--color-blue-50)",
    "--color-info-dark": "var(--color-blue-800)",
    "--color-info-light": "var(--color-blue-100)",
    "--logo-filter": "brightness(0) invert(1)",
  },
  cyberpunk: {
    "--color-primary": "var(--color-fuchsia-500)",
    "--color-primary-contrast": "var(--color-fuchsia-50)",
    "--color-primary-hover": "var(--color-fuchsia-600)",
    "--color-accent": "var(--color-cyan-400)",
    "--color-accent-contrast": "var(--color-cyan-950)",
    "--color-accent-hover": "var(--color-cyan-500)",
    "--color-border": "var(--color-fuchsia-900)",
    "--color-background": "var(--color-slate-950)",
    "--color-foreground": "var(--color-slate-900)",
    "--color-text": "var(--color-fuchsia-50)",
    "--color-text-secondary": "var(--color-fuchsia-200)",
    "--color-success": "var(--color-lime-500)",
    "--color-success-contrast": "var(--color-lime-50)",
    "--color-success-dark": "var(--color-lime-800)",
    "--color-success-light": "var(--color-lime-100)",
    "--color-error": "var(--color-rose-500)",
    "--color-error-contrast": "var(--color-rose-50)",
    "--color-error-dark": "var(--color-rose-800)",
    "--color-error-light": "var(--color-rose-100)",
    "--color-warning": "var(--color-yellow-400)",
    "--color-warning-contrast": "var(--color-yellow-50)",
    "--color-warning-dark": "var(--color-yellow-800)",
    "--color-warning-light": "var(--color-yellow-100)",
    "--color-info": "var(--color-violet-400)",
    "--color-info-contrast": "var(--color-violet-50)",
    "--color-info-dark": "var(--color-violet-800)",
    "--color-info-light": "var(--color-violet-100)",
    "--logo-filter": "brightness(0) invert(1)",
  },
  forest: {
    "--color-primary": "var(--color-emerald-600)",
    "--color-primary-contrast": "var(--color-emerald-50)",
    "--color-primary-hover": "var(--color-emerald-700)",
    "--color-accent": "var(--color-orange-400)",
    "--color-accent-contrast": "var(--color-orange-950)",
    "--color-accent-hover": "var(--color-orange-500)",
    "--color-border": "var(--color-emerald-800)",
    "--color-background": "var(--color-stone-950)",
    "--color-foreground": "var(--color-stone-900)",
    "--color-text": "var(--color-stone-50)",
    "--color-text-secondary": "var(--color-stone-300)",
    "--color-success": "var(--color-lime-500)",
    "--color-success-contrast": "var(--color-lime-50)",
    "--color-success-dark": "var(--color-lime-800)",
    "--color-success-light": "var(--color-lime-100)",
    "--color-error": "var(--color-red-500)",
    "--color-error-contrast": "var(--color-red-50)",
    "--color-error-dark": "var(--color-red-800)",
    "--color-error-light": "var(--color-red-100)",
    "--color-warning": "var(--color-amber-500)",
    "--color-warning-contrast": "var(--color-amber-50)",
    "--color-warning-dark": "var(--color-amber-800)",
    "--color-warning-light": "var(--color-amber-100)",
    "--color-info": "var(--color-sky-500)",
    "--color-info-contrast": "var(--color-sky-50)",
    "--color-info-dark": "var(--color-sky-800)",
    "--color-info-light": "var(--color-sky-100)",
    "--logo-filter": "brightness(0) invert(1)",
  },
};
